---
# tasks file for kubeadm
- name: Check if Kubernetes apt-key exists
  stat:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.asc
  register: kubernetes_apt_key

- name: Add Kubernetes apt-key
  get_url:
    url: "{{ kubernetes_apt_gpg_key }}"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: "0644"
    force: true
  when: not kubernetes_apt_key.stat.exists

- name: Check if Kubernetes APT repository exists
  command: grep -r "{{ kubernetes_repo_url }}" /etc/apt/sources.list /etc/apt/sources.list.d/
  register: repo_check
  check_mode: no
  ignore_errors: true
  changed_when: false

- name: Add Kubernetes APT repository
  apt_repository:
    repo: "{{ kubernetes_apt_repo }}"
    state: present
    update_cache: yes
  when: repo_check.rc != 0

- name: Install Kubeadm
  apt:
    name: kubeadm
    state: present