---
# defaults file for roles/cni-plugins
cni_plugin_version: "v1.5.1"

cni_plugin_url: "https://github.com/containernetworking/plugins/releases/download/{{ cni_plugin_version }}/cni-plugins-linux-amd64-{{ cni_plugin_version }}.tgz"

cni_install_dir: "/opt/cni/bin"

cni_temp_dir: "/tmp/cni_plugins"

cni_plugin_file: "{{ cni_install_dir }}/bridge"