---
# tasks file for kubelet
- name: Ensure dependencies are installed.
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - python3-apt
    - gpg
    - apt-transport-https
    - ca-certificates
    - curl

- name: Ensure the /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Kubernetes apt-key
  get_url:
    url: "{{ kubernetes_apt_gpg_key }}"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: "0644"
    force: true

- name: Add Kubernetes APT repository
  apt_repository:
    repo: "{{ kubernetes_apt_repo }}"
    state: present
    update_cache: yes

- name: Install Kubelet
  apt:
    name: kubelet
    state: present