---
# defaults file for kubectl
kubernetes_version: 'v1.30'

kubernetes_repo_url: "https://pkgs.k8s.io/core:/stable:/"

kubernetes_apt_repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] {{ kubernetes_repo_url }}{{ kubernetes_version }}/deb/ /

kubernetes_apt_gpg_key: "{{ kubernetes_repo_url }}{{ kubernetes_version }}/deb/Release.key"