---
# defaults file for roles/coba
kubernetes_repo_url: 'https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/'
kubernetes_gpg_key_url: 'https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key'
kubernetes_version: 'v1.30.2'
