---
# tasks file for roles/cni-plugins
- name: Create temporary directory for CNI plugins
  file:
    path: "{{ cni_temp_dir }}"
    state: directory

- name: Download CNI plugin
  get_url:
    url: "{{ cni_plugin_url }}"
    dest: "{{ cni_temp_dir }}/cni-plugins.tgz"

- name: Ensure CNI install directory exists
  file:
    path: "{{ cni_install_dir }}"
    state: directory
    mode: "0755"

- name: Extract CNI plugin
  unarchive:
    src: "{{ cni_temp_dir }}/cni-plugins.tgz"
    dest: "{{ cni_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Clean up temporary files
  file:
    path: "{{ cni_temp_dir }}"
    state: absent