---
# tasks file for roles/containerd
- name: Check if containerd binary exists
  stat:
    path: "{{ containerd_install_dir }}/containerd"
  register: containerd_binary

- name: Create temporary directory for containerd
  file:
    path: "{{ containerd_temp_dir }}"
    state: directory
  when: not containerd_binary.stat.exists

- name: Download containerd binary
  get_url:
    url: "{{ containerd_download_url }}"
    dest: "{{ containerd_temp_dir }}/containerd.tar.gz"
  when: not containerd_binary.stat.exists

- name: Extract containerd binary
  unarchive:
    src: "{{ containerd_temp_dir }}/containerd.tar.gz"
    dest: "{{ containerd_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: not containerd_binary.stat.exists

- name: Ensure systemd directory exists
  file:
    path: "{{ systemd_dir }}"
    state: directory
    mode: "0755"

- name: Download containerd service file
  get_url:
    url: "{{ containerd_service_url }}"
    dest: "{{ containerd_service_dest }}"
    mode: "0644"

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start containerd service
  systemd:
    name: containerd
    enabled: yes
    state: started

- name: Create containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: Copy containerd config files
  copy:
    src: config.toml
    dest: "{{ containerd_config_file }}"
    owner: root
    group: root
    mode: "0644"

- name: Clean up temporary files
  file:
    path: "{{ containerd_temp_dir }}"
    state: absent